"""Build data/statcast.duckdb from the cached raw files, then run the validation checks.

Run src/fetch_data.py first. Writes docs/validation_report.md and exits non-zero if
any FAIL-level check flags rows.
"""

import os
import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
SEASONS = range(2021, 2027)
RAW_PREFIXES = ["savant_custom", "savant_batted_ball", "savant_expected", "statsapi_team_pa"]
DB_PATH = ROOT / "data" / "statcast.duckdb"
REPORT_PATH = ROOT / "docs" / "validation_report.md"


def main() -> None:
    os.chdir(ROOT)  # SQL files use paths relative to the repo root
    missing = [f"{prefix}_{season}.csv" for prefix in RAW_PREFIXES for season in SEASONS
               if not (ROOT / "data" / "raw" / f"{prefix}_{season}.csv").exists()]
    if missing:
        sys.exit(f"Missing raw files (run src/fetch_data.py first): {', '.join(missing)}")
    con = duckdb.connect(str(DB_PATH))
    con.execute((ROOT / "sql" / "01_build_tables.sql").read_text(encoding="utf-8"))

    for table in ["stg_savant_custom", "stg_batted_ball", "stg_team_pa", "xcheck_expected", "player_season", "season_pairs"]:
        print(f"{table:<20} {con.table(table).count('*').fetchone()[0]:>6} rows")

    results = con.execute((ROOT / "sql" / "02_validation.sql").read_text(encoding="utf-8")).fetchall()
    write_report(results)

    print("\nValidation:")
    for _, name, flagged, checked, result in results:
        print(f"  [{result:<4}] {name}: {flagged} / {checked}")
    print(f"\nReport written to {REPORT_PATH.relative_to(ROOT)}")

    if any(result == "FAIL" for *_, result in results):
        sys.exit(1)


def write_report(results: list[tuple]) -> None:
    lines = [
        "# Validation report",
        "",
        "Generated by `src/build_db.py`. "
        "Checks are defined in [`sql/02_validation.sql`](../sql/02_validation.sql).",
        "",
        "| # | Check | Flagged | Checked | Result |",
        "|---|---|---:|---:|---|",
    ]
    lines += [f"| {n} | {name} | {flagged} | {checked} | {result} |" for n, name, flagged, checked, result in results]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
